# Generated by Django 5.1.2 on 2024-11-14 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product_views_counter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num_version",
                    models.IntegerField(
                        blank=True,
                        help_text="Введите номер версии",
                        null=True,
                        verbose_name="Номер версии",
                    ),
                ),
                (
                    "name_version",
                    models.CharField(
                        help_text="Укажите название версии",
                        max_length=100,
                        verbose_name="Наименование версии",
                    ),
                ),
                (
                    "status_version",
                    models.BooleanField(default=True, verbose_name="Статус версии"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product",
                        to="product.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия",
                "verbose_name_plural": "Версии",
                "ordering": ["product", "num_version"],
            },
        ),
    ]
